#     This is an FTP Deploy Pipeline for GitHub Action.
#     We are using this pipeline to Build and Deploy a React application
#     on to Hostinger platform where the application will be hosted

on:
  push:
    branches: [main, deploy]

name: Build and Deploy to Hostinger

jobs:
  
  ftp-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    # Building the React Application
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm test
    - run: npm run build --if-present


    # FTP the build artifacts to Hostinger
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.alif.link
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
  
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
