#     This is an FTP Deploy Pipeline for GitHub Action.
#     We are using this pipeline to Build and Deploy a React application
#     on to Hostinger platform where the application will be hosted

on:
  push:
    branches: [deploy]

name: Build and Deploy to Hostinger

jobs:
  
  hostinger-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
  
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: vancoleague.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
    
